# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: reply 0.5.1 ruby lib

Gem::Specification.new do |s|
  s.name = "reply"
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Sebastian Porto"]
  s.date = "2014-03-07"
  s.description = "An standarized reply object"
  s.email = "s@porto5.com"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "lib/reply.rb",
    "lib/reply/reply.rb",
    "readme.md",
    "reply.gemspec",
    "spec/lib/reply/reply_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/sporto/reply"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "An standarized reply object"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<active_attr>, ["~> 0.8"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<bogus>, ["~> 0.1"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
    else
      s.add_dependency(%q<active_attr>, ["~> 0.8"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<bogus>, ["~> 0.1"])
      s.add_dependency(%q<guard-rspec>, ["~> 3.1"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.14"])
    end
  else
    s.add_dependency(%q<active_attr>, ["~> 0.8"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<bogus>, ["~> 0.1"])
    s.add_dependency(%q<guard-rspec>, ["~> 3.1"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.14"])
  end
end

